// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/books"
	"entdemo/ent/predicate"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BooksUpdate is the builder for updating Books entities.
type BooksUpdate struct {
	config
	hooks    []Hook
	mutation *BooksMutation
}

// Where appends a list predicates to the BooksUpdate builder.
func (bu *BooksUpdate) Where(ps ...predicate.Books) *BooksUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetBookName sets the "book_name" field.
func (bu *BooksUpdate) SetBookName(s string) *BooksUpdate {
	bu.mutation.SetBookName(s)
	return bu
}

// SetAuthor sets the "author" field.
func (bu *BooksUpdate) SetAuthor(s string) *BooksUpdate {
	bu.mutation.SetAuthor(s)
	return bu
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (bu *BooksUpdate) SetNillableAuthor(s *string) *BooksUpdate {
	if s != nil {
		bu.SetAuthor(*s)
	}
	return bu
}

// SetPublishDate sets the "publish_date" field.
func (bu *BooksUpdate) SetPublishDate(s string) *BooksUpdate {
	bu.mutation.SetPublishDate(s)
	return bu
}

// Mutation returns the BooksMutation object of the builder.
func (bu *BooksUpdate) Mutation() *BooksMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BooksUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, BooksMutation](ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BooksUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BooksUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BooksUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BooksUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   books.Table,
			Columns: books.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: books.FieldID,
			},
		},
	}
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.BookName(); ok {
		_spec.SetField(books.FieldBookName, field.TypeString, value)
	}
	if value, ok := bu.mutation.Author(); ok {
		_spec.SetField(books.FieldAuthor, field.TypeString, value)
	}
	if value, ok := bu.mutation.PublishDate(); ok {
		_spec.SetField(books.FieldPublishDate, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{books.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BooksUpdateOne is the builder for updating a single Books entity.
type BooksUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BooksMutation
}

// SetBookName sets the "book_name" field.
func (buo *BooksUpdateOne) SetBookName(s string) *BooksUpdateOne {
	buo.mutation.SetBookName(s)
	return buo
}

// SetAuthor sets the "author" field.
func (buo *BooksUpdateOne) SetAuthor(s string) *BooksUpdateOne {
	buo.mutation.SetAuthor(s)
	return buo
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (buo *BooksUpdateOne) SetNillableAuthor(s *string) *BooksUpdateOne {
	if s != nil {
		buo.SetAuthor(*s)
	}
	return buo
}

// SetPublishDate sets the "publish_date" field.
func (buo *BooksUpdateOne) SetPublishDate(s string) *BooksUpdateOne {
	buo.mutation.SetPublishDate(s)
	return buo
}

// Mutation returns the BooksMutation object of the builder.
func (buo *BooksUpdateOne) Mutation() *BooksMutation {
	return buo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BooksUpdateOne) Select(field string, fields ...string) *BooksUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Books entity.
func (buo *BooksUpdateOne) Save(ctx context.Context) (*Books, error) {
	return withHooks[*Books, BooksMutation](ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BooksUpdateOne) SaveX(ctx context.Context) *Books {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BooksUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BooksUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BooksUpdateOne) sqlSave(ctx context.Context) (_node *Books, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   books.Table,
			Columns: books.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: books.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Books.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, books.FieldID)
		for _, f := range fields {
			if !books.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != books.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.BookName(); ok {
		_spec.SetField(books.FieldBookName, field.TypeString, value)
	}
	if value, ok := buo.mutation.Author(); ok {
		_spec.SetField(books.FieldAuthor, field.TypeString, value)
	}
	if value, ok := buo.mutation.PublishDate(); ok {
		_spec.SetField(books.FieldPublishDate, field.TypeString, value)
	}
	_node = &Books{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{books.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
