// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"entdemo/ent/books"
	"entdemo/ent/predicate"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBooks = "Books"
)

// BooksMutation represents an operation that mutates the Books nodes in the graph.
type BooksMutation struct {
	config
	op            Op
	typ           string
	id            *int
	book_name     *string
	author        *string
	publish_date  *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Books, error)
	predicates    []predicate.Books
}

var _ ent.Mutation = (*BooksMutation)(nil)

// booksOption allows management of the mutation configuration using functional options.
type booksOption func(*BooksMutation)

// newBooksMutation creates new mutation for the Books entity.
func newBooksMutation(c config, op Op, opts ...booksOption) *BooksMutation {
	m := &BooksMutation{
		config:        c,
		op:            op,
		typ:           TypeBooks,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBooksID sets the ID field of the mutation.
func withBooksID(id int) booksOption {
	return func(m *BooksMutation) {
		var (
			err   error
			once  sync.Once
			value *Books
		)
		m.oldValue = func(ctx context.Context) (*Books, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Books.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBooks sets the old Books of the mutation.
func withBooks(node *Books) booksOption {
	return func(m *BooksMutation) {
		m.oldValue = func(context.Context) (*Books, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BooksMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BooksMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BooksMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *BooksMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Books.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetBookName sets the "book_name" field.
func (m *BooksMutation) SetBookName(s string) {
	m.book_name = &s
}

// BookName returns the value of the "book_name" field in the mutation.
func (m *BooksMutation) BookName() (r string, exists bool) {
	v := m.book_name
	if v == nil {
		return
	}
	return *v, true
}

// OldBookName returns the old "book_name" field's value of the Books entity.
// If the Books object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BooksMutation) OldBookName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldBookName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldBookName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldBookName: %w", err)
	}
	return oldValue.BookName, nil
}

// ResetBookName resets all changes to the "book_name" field.
func (m *BooksMutation) ResetBookName() {
	m.book_name = nil
}

// SetAuthor sets the "author" field.
func (m *BooksMutation) SetAuthor(s string) {
	m.author = &s
}

// Author returns the value of the "author" field in the mutation.
func (m *BooksMutation) Author() (r string, exists bool) {
	v := m.author
	if v == nil {
		return
	}
	return *v, true
}

// OldAuthor returns the old "author" field's value of the Books entity.
// If the Books object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BooksMutation) OldAuthor(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAuthor is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAuthor requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAuthor: %w", err)
	}
	return oldValue.Author, nil
}

// ResetAuthor resets all changes to the "author" field.
func (m *BooksMutation) ResetAuthor() {
	m.author = nil
}

// SetPublishDate sets the "publish_date" field.
func (m *BooksMutation) SetPublishDate(s string) {
	m.publish_date = &s
}

// PublishDate returns the value of the "publish_date" field in the mutation.
func (m *BooksMutation) PublishDate() (r string, exists bool) {
	v := m.publish_date
	if v == nil {
		return
	}
	return *v, true
}

// OldPublishDate returns the old "publish_date" field's value of the Books entity.
// If the Books object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BooksMutation) OldPublishDate(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPublishDate is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPublishDate requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPublishDate: %w", err)
	}
	return oldValue.PublishDate, nil
}

// ResetPublishDate resets all changes to the "publish_date" field.
func (m *BooksMutation) ResetPublishDate() {
	m.publish_date = nil
}

// Where appends a list predicates to the BooksMutation builder.
func (m *BooksMutation) Where(ps ...predicate.Books) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the BooksMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *BooksMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Books, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *BooksMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *BooksMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Books).
func (m *BooksMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BooksMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.book_name != nil {
		fields = append(fields, books.FieldBookName)
	}
	if m.author != nil {
		fields = append(fields, books.FieldAuthor)
	}
	if m.publish_date != nil {
		fields = append(fields, books.FieldPublishDate)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BooksMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case books.FieldBookName:
		return m.BookName()
	case books.FieldAuthor:
		return m.Author()
	case books.FieldPublishDate:
		return m.PublishDate()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BooksMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case books.FieldBookName:
		return m.OldBookName(ctx)
	case books.FieldAuthor:
		return m.OldAuthor(ctx)
	case books.FieldPublishDate:
		return m.OldPublishDate(ctx)
	}
	return nil, fmt.Errorf("unknown Books field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BooksMutation) SetField(name string, value ent.Value) error {
	switch name {
	case books.FieldBookName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetBookName(v)
		return nil
	case books.FieldAuthor:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAuthor(v)
		return nil
	case books.FieldPublishDate:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPublishDate(v)
		return nil
	}
	return fmt.Errorf("unknown Books field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BooksMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BooksMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BooksMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Books numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BooksMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BooksMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BooksMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Books nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BooksMutation) ResetField(name string) error {
	switch name {
	case books.FieldBookName:
		m.ResetBookName()
		return nil
	case books.FieldAuthor:
		m.ResetAuthor()
		return nil
	case books.FieldPublishDate:
		m.ResetPublishDate()
		return nil
	}
	return fmt.Errorf("unknown Books field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BooksMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BooksMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BooksMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BooksMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BooksMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BooksMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BooksMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Books unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BooksMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Books edge %s", name)
}
