// Code generated by ent, DO NOT EDIT.

package ent

import (
	"entdemo/ent/books"
	"entdemo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	booksFields := schema.Books{}.Fields()
	_ = booksFields
	// booksDescAuthor is the schema descriptor for author field.
	booksDescAuthor := booksFields[1].Descriptor()
	// books.DefaultAuthor holds the default value on creation for the author field.
	books.DefaultAuthor = booksDescAuthor.Default.(string)
}
